from pydantic import ConfigDict, Field
from typing import Optional

from sensor.models.config.sensor_config import SensorConfig


class RNGConfig(SensorConfig):
    model_config = ConfigDict(
        title="RNG Configuration"
    )

    sensor_name: Optional[str] = Field(
        title="Sensor Name",
        description="A human-readable name for the sensor.",
        default="RNG"
    )
    maximum: float = Field(
        title="Maximum",
        description="The maximum float value that can be generated by the random number generator",
        default=100.0
    )
    minimum: float = Field(
        title="Minimum",
        description="The minimum float value that can be generated by the random number generator",
        default=0.0
    )
